[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pyccx"
version = "0.0.0"
authors = [
  { name="Sahand Nazarzadeh", email="sahand.nazarzadeh@gmail.com" },
]
description = "Python Crypto Currency Exchanges"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "pandas",
    "requests"
]
